I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    image chapter2_0 = conner.png
  File "game/script.rpy", line 30, in <module>
    image chapter2_0 = conner.png
NameError: name 'conner' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    image chapter2_0 = conner.png
  File "/Users/brittanybrassell/repos/pills/renpy-6.99.10-sdk/renpy/ast.py", line 897, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/brittanybrassell/repos/pills/renpy-6.99.10-sdk/renpy/python.py", line 1601, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 30, in <module>
    image chapter2_0 = conner.png
NameError: name 'conner' is not defined

Darwin-15.5.0-x86_64-i386-64bit
Ren'Py 6.99.10.1227
pills 0.0
